### ISSUE TITLE
git branching

### ISSUE THREAD

**Issue by nvartolomei** [9-volt/Words-Frequency-Visualization#11]
That moment when development is going on gh-pages branch

![](http://www.quickmeme.com/img/f7/f7be5f9e45d8ec2fda05e4a95286692ea0c0c1ec40eb873af1f4ff8d1dfd2b10.jpg)

**Comment by bumbu** [comment]
I'm sorry. I'll never ever do it again. Thank you for being so kind to explain to me why my life sucks.
Now everything makes sense.
