### ISSUE TITLE
Hovering over one graph point doesn't show the tooltip in firefox

### ISSUE THREAD

**Issue by minivan** [9-volt/Words-Frequency-Visualization#9]
Running FF 28.0

**Comment by bumbu** [comment]
There were 2 bugs:
- mouse events may differ in different browsers and used attribute (offsetX) is not available in FF
- [SVG's getTotalLength is buggy in FF 28](https://bugzilla.mozilla.org/show_bug.cgi?id=984796)

I solved first one, second one will be solved with next FF. After that everything should work ok.

**Comment by bumbu** [comment]
Firefox 29 is out, bug fixed
